const app=document.getElementById("app");
const KEY="englishHomeV2State";
let S=JSON.parse(localStorage.getItem(KEY)||'{"done":[1],"fav":[],"mistakes":[],"day":2}');
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function speak(t){if(!window.speechSynthesis)return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function shell(body,active="home"){app.innerHTML=`<div class="app"><header class="top"><div class="brand">英语之家</div><div class="sub">零基础 → CEFR → IELTS → Advanced English</div></header><main class="content">${body}</main><nav class="nav"><div class="navin">${[["home","首页"],["today","今日"],["skills","能力"],["resources","资源"],["me","我的"]].map(x=>`<button class="${active==x[0]?"active":""}" onclick="go('${x[0]}')">${x[1]}</button>`).join("")}</div></nav></div>`}
function back(){return `<button class="btn ghost" onclick="go('home')">← 返回</button>`}
function pct(){return Math.round(S.done.length/15*100)}
function home(){shell(`<section class="card hero"><div class="kicker">YOUR ENGLISH PATH</div><h1>真正开始学英语</h1><p class="muted">课程内容、练习、朗读、阅读、视频资源和复习全部放在这里。</p><div class="progress"><i style="width:${pct()}%"></i></div><p>Pre-A1 当前进度：${pct()}%</p><button class="btn" onclick="go('today')">开始今天 Day ${S.day}</button></section>
<section class="card"><h2>完整能力体系</h2><div class="grid">${CURRICULUM.skills.map((x,i)=>`<button class="tile" onclick="go('skill',${i})"><b>${x}</b><span>${["听清并读准","正确写出","理解和运用","理解为什么","听懂声音","组织并说出","理解文本","自己表达","建立英语结构","场景自然使用"][i]}</span></button>`).join("")}</div></section>
<section class="card"><h2>长期路线</h2>${CURRICULUM.levels.map(x=>`<div class="resource"><b>${x[0]}｜${x[1]}</b><p class="muted">${x[2]}</p></div>`).join("")}</section>`)}
function today(){let L=LESSONS[S.day]||LESSONS[2];shell(`${back()}<section class="card hero"><div class="kicker">${L? "DAY "+S.day:"TODAY"}</div><h1>${L.title}</h1><p class="muted">${L.goal}</p></section>${L.sections?.length?L.sections.map((s,i)=>`<section class="card"><h2>${i+1}. ${s.title}</h2>${s.body.map(x=>`<p>${x}</p>`).join("")}${s.examples.map(e=>`<div class="example"><b>${e}</b><br><button class="btn secondary" onclick="speak('${e.replace(/'/g,"\\'")}')">🔊 朗读</button></div>`).join("")}</section>`).join(""):`<section class="card"><h2>这个 Day 的完整内容正在扩展</h2><p>当前版本先把 Day 2 做成完整示范，后续每日课程按同样结构继续加入。</p></section>`}
${L.practice?.length?`<section class="card"><h2>今天的练习</h2>${L.practice.map((q,i)=>`<div class="card" id="q${i}" style="box-shadow:none;padding:10px"><b>${i+1}. ${q[0]}</b>${q[1].map((o,j)=>`<button class="answer" onclick="quiz(${i},${j},${q[2]},this,'${esc(q[3])}')">${o}</button>`).join("")}<div id="e${i}"></div></div>`).join("")}</section>`:""}
<section class="card"><h2>今天的 10 条能力线</h2><p>学完语法后，继续：词汇 → 发音 → 听力 → 口语 → 阅读 → 写作 → 英语思维 → 语用。</p><div class="row"><button class="btn" onclick="go('vocab')">词汇</button><button class="btn secondary" onclick="go('grammar')">语法</button><button class="btn secondary" onclick="go('pron')">发音</button></div></section>
<section class="card"><button class="btn" onclick="finishDay()">完成今天课程</button></section>`,"today")}
function quiz(i,j,a,el,ex){document.querySelectorAll("#q"+i+" .answer").forEach(x=>x.disabled=true);let e=document.getElementById("e"+i);if(j===a){el.classList.add("correct");e.innerHTML=`<p>✓ 正确。${ex}</p>`}else{el.classList.add("wrong");S.mistakes.push({day:S.day,q:i});save();e.innerHTML=`<p>✗ 再看一次：${ex}</p>`}}
function finishDay(){if(!S.done.includes(S.day))S.done.push(S.day);if(S.day<15)S.day++;save();alert("今天完成并已保存。下一天是 Day "+S.day);go("today")}
function skills(){shell(`${back()}<section class="card"><h1>10 条能力线</h1><p>这里不是只有名称，每条能力线都对应具体训练。</p></section><div class="grid">${CURRICULUM.skills.map((x,i)=>`<button class="tile" onclick="go('skill',${i})"><b>${x}</b><span>进入训练</span></button>`).join("")}</div>`,"skills")}
function skill(i){let names=CURRICULUM.skills;let x=names[i];let bodies={
"发音":`<h2>发音训练</h2><p>先听 → 再看 IPA → 再跟读 → 再放进句子。</p>${["I /aɪ/","like /laɪk/","live /lɪv/","she /ʃiː/","you /juː/"].map(t=>{let w=t.split(" ")[0];return `<div class="resource"><span class="word">${t}</span><br><button class="btn" onclick="speak('${w}')">🔊 朗读</button></div>`}).join("")}`,
"拼写":`<h2>拼写训练</h2><p>拼写不是背单词的附属能力。先听声音，再写字母，再核对。</p>${["like","live","want","learn","coffee"].map((w,i)=>`<div class="resource"><b>${i+1}. ${w}</b><input id="sp${i}" placeholder="自己输入拼写"><button class="btn" onclick="spell('${w}',${i})">检查</button><div id="se${i}"></div></div>`).join("")}`,
"词汇":`<h2>词汇系统</h2><p>每个词同时学习：词义、词性、发音、拼写、搭配、例句、语境。</p>${VOCABULARY.map(v=>`<div class="resource"><div class="word">${v.w}</div><div class="ipa">${v.ipa}</div><b>${v.cn}</b><p>${v.ex}</p><p class="muted">${v.why}</p><button class="btn" onclick="speak('${v.w}')">🔊 单词</button> <button class="btn secondary" onclick="speak('${v.ex.replace(/'/g,"\\'")}')">🔊 例句</button></div>`).join("")}`,
"语法":`<h2>语法系统</h2>${GRAMMAR_LIBRARY.map(g=>`<div class="resource"><h3>${g.title}</h3><p>${g.rule}</p>${g.examples.map(e=>`<div class="example">${e}<br><button class="btn secondary" onclick="speak('${e.replace(/'/g,"\\'")}')">🔊 朗读</button></div>`).join("")}</div>`).join("")}`,
"听力":`<h2>听力系统</h2><p>先盲听，再看文字，再逐句听，再跟读。以后每个阶段都会有不同难度。</p><div class="resource"><button class="btn" onclick="speak('I live in Qingdao. I like coffee. I want to learn English.')">🔊 播放今日材料</button><p>I live in Qingdao. I like coffee. I want to learn English.</p></div>`,
"口语":`<h2>口语系统</h2><p>今天先使用浏览器朗读作为输入，之后继续加入跟读、录音和对比训练。</p>${["Hi, I’m Wang Yu.","I live in Qingdao.","I like coffee.","I want to learn English."].map(e=>`<div class="resource"><b>${e}</b><br><button class="btn" onclick="speak('${e}')">🔊 听</button></div>`).join("")}`,
"阅读":`<h2>阅读系统</h2><div class="resource"><h3>My English Goal</h3><p>My name is Wang Yu. I live in Qingdao. I am learning English because I want to communicate more confidently. I study a little every day. I learn words, grammar, pronunciation and useful expressions. I do not want to memorize English without understanding it.</p><p><b>问题：</b>Why is Wang Yu learning English?</p><button class="answer" onclick="this.classList.add('correct')">Because she wants to communicate more confidently.</button></div>`,
"写作":`<h2>写作系统</h2><p>从句子 → 短段落 → 日记 → 工作表达 → 观点文章。</p><textarea placeholder="今天试着写 3 句英文：我是谁、我住在哪里、我为什么学英语。"></textarea><button class="btn" onclick="alert('已完成一次写作练习。下一步可以把你的答案发给我，我会按当前等级纠正。')">完成练习</button>`,
"英语思维":`<h2>英语思维</h2><div class="note"><b>中文：</b>我想学英语。<br><b>英语结构：</b>I want to learn English.<br><b>关键：</b>want to + 动词原形，而不是逐字翻译。</div><div class="note"><b>中文：</b>我住在青岛。<br><b>英语结构：</b>I live in Qingdao.<br><b>关键：</b>live 是普通动词，地点前这里用 in。</div>`,
"语用与文化":`<h2>语用与文化</h2>${["Hi, I’m Wang Yu.","Nice to meet you.","I’m from China.","I live in Qingdao.","Could you say that again?","Sorry, I didn’t catch that."].map(e=>`<div class="resource"><b>${e}</b><br><button class="btn secondary" onclick="speak('${e}')">🔊 听</button></div>`).join("")}`
};shell(`${back()}<section class="card hero"><div class="kicker">SKILL</div><h1>${x}</h1><p class="muted">从基础开始逐级训练，最终贯通 CEFR、IELTS 和高级英语。</p></section><section class="card">${bodies[x]}</section>`,"skills")}
function spell(w,i){let v=document.getElementById("sp"+i).value.trim().toLowerCase();document.getElementById("se"+i).innerHTML=v===w?'<p class="correct">✓ 正确</p>':`<p class="wrong">✗ 正确答案：${w}</p>`}
function grammar(){skill(CURRICULUM.skills.indexOf("语法"))}
function pron(){skill(CURRICULUM.skills.indexOf("发音"))}
function vocab(){skill(CURRICULUM.skills.indexOf("词汇"))}
function resources(){shell(`${back()}<section class="card"><h1>真实英语资源库</h1><p>这里接入的是公开的官方学习资源入口。我们不把别人的受版权保护的视频文件复制进你的 GitHub，而是让你从自己的页面进入原始资源。</p></section>${RESOURCES.map(r=>`<div class="card"><span class="tag">${r.level}</span><span class="tag">${r.type}</span><h2>${r.title}</h2><p>${r.desc}</p><a class="btn" href="${r.url}" target="_blank" rel="noopener">打开学习资源 ↗</a></div>`).join("")}`,"resources")}
function me(){shell(`${back()}<section class="card"><h1>我的学习</h1><p>已完成 Day：${S.done.join("、")}</p><p>当前 Day：${S.day}</p><p>错题记录：${S.mistakes.length}</p><p>收藏：${S.fav.length}</p></section><section class="card"><h2>间隔复习</h2><p>当天 → 次日 → 第 3 天 → 第 7 天 → 第 14 天 → 第 30 天。</p><p class="muted">后续会把每个词、语法点和错题自动排进复习队列。</p></section><section class="card"><h2>每日笔记</h2><p>今天学了什么：</p><textarea placeholder="写下今天真正理解的 3-5 个重点。"></textarea></section>`,"me")}
function go(x,arg){if(x==="home")home();else if(x==="today")today();else if(x==="skills")skills();else if(x==="skill")skill(arg);else if(x==="resources")resources();else if(x==="me")me();else if(x==="grammar")grammar();else if(x==="pron")pron();else if(x==="vocab")vocab();else home()}
home();